// Song Database - TuyenTapThanhCa LAUDATO SI
// Extracted from LAUDATO SI.pdf with 599 songs
// Organized by mass slots (NL/DL/HL/KL) and liturgical seasons

export const SONGS = [
  // --- NHẬP LỄ (48 songs) ---
  { id: "ls-nl-1", name: "Bến bờ yêu thương", tags: ["NL"], season: "ORDINARY", page: "8" },
  { id: "ls-nl-2", name: "Bước vào", tags: ["NL"], season: "ORDINARY", page: "10" },
  { id: "ls-nl-3", name: "Ca lên đi 10", tags: ["NL"], season: "ORDINARY", page: "14" },
  { id: "ls-nl-4", name: "Ca lên đi 3", tags: ["NL"], season: "ORDINARY", page: "35" },
  { id: "ls-nl-5", name: "Ca lên đi 4", tags: ["NL"], season: "ORDINARY", page: "12" },
  { id: "ls-nl-6", name: "Ca lên đi 7", tags: ["NL"], season: "ORDINARY", page: "13" },
  { id: "ls-nl-7", name: "Ca ngợi Chúa", tags: ["NL"], season: "ORDINARY", page: "15" },
  { id: "ls-nl-8", name: "Chúc tụng Chúa", tags: ["NL"], season: "ORDINARY", page: "16" },
  { id: "ls-nl-9", name: "Chung lời tạ ơn", tags: ["NL"], season: "ORDINARY", page: "17" },
  { id: "ls-nl-10", name: "Con hân hoan 1", tags: ["NL"], season: "ORDINARY", page: "18" },
  { id: "ls-nl-11", name: "Con hân hoan 2", tags: ["NL"], season: "ORDINARY", page: "19" },
  { id: "ls-nl-12", name: "Con sẽ bước lên bàn thờ", tags: ["NL"], season: "ORDINARY", page: "20" },
  { id: "ls-nl-13", name: "Con sẽ hân hoan", tags: ["NL"], season: "ORDINARY", page: "21" },
  { id: "ls-nl-14", name: "Cửa công chính", tags: ["NL"], season: "ORDINARY", page: "22" },
  { id: "ls-nl-15", name: "Đến trước Nhan Ngài", tags: ["NL"], season: "ORDINARY", page: "23" },
  { id: "ls-nl-16", name: "Đi về nhà Chúa 1", tags: ["NL"], season: "ORDINARY", page: "24" },
  { id: "ls-nl-17", name: "Đi về nhà Chúa 2", tags: ["NL"], season: "ORDINARY", page: "26" },
  { id: "ls-nl-18", name: "Hát lên bài ca", tags: ["NL"], season: "ORDINARY", page: "27" },
  { id: "ls-nl-19", name: "Hãy đến", tags: ["NL"], season: "ORDINARY", page: "29" },
  { id: "ls-nl-20", name: "Hãy đến dâng khúc cảm tạ", tags: ["NL"], season: "ORDINARY", page: "30" },
  { id: "ls-nl-21", name: "Hãy hát khen Chúa", tags: ["NL"], season: "ORDINARY", page: "28" },
  { id: "ls-nl-22", name: "Hãy hát lên", tags: ["NL"], season: "ORDINARY", page: "43" },
  { id: "ls-nl-23", name: "Hòa tiếng hát ngợi khen", tags: ["NL"], season: "ORDINARY", page: "31" },
  { id: "ls-nl-24", name: "Hỡi thế trần", tags: ["NL"], season: "ORDINARY", page: "32" },
  { id: "ls-nl-25", name: "Khúc tân ca", tags: ["NL"], season: "ORDINARY", page: "33" },
  { id: "ls-nl-26", name: "Lên đền thánh 1", tags: ["NL"], season: "ORDINARY", page: "34" },
  { id: "ls-nl-27", name: "Lên đền thánh 2", tags: ["NL"], season: "ORDINARY", page: "36" },
  { id: "ls-nl-28", name: "Lên núi Sion", tags: ["NL"], season: "ORDINARY", page: "37" },
  { id: "ls-nl-29", name: "Lời ca dâng", tags: ["NL"], season: "ORDINARY", page: "38" },
  { id: "ls-nl-30", name: "Ngợi ca", tags: ["NL"], season: "ORDINARY", page: "39" },
  { id: "ls-nl-31", name: "Niềm vui thiết tha", tags: ["NL"], season: "ORDINARY", page: "40" },
  { id: "ls-nl-32", name: "Nơi nhà Chúa", tags: ["NL"], season: "ORDINARY", page: "42" },
  { id: "ls-nl-33", name: "Tâm tư hân hoan", tags: ["NL"], season: "ORDINARY", page: "41" },
  { id: "ls-nl-34", name: "Tiến vào thánh cung", tags: ["NL"], season: "ORDINARY", page: "44" },
  { id: "ls-nl-35", name: "Tiến về nhà Chúa", tags: ["NL"], season: "ORDINARY", page: "46" },
  { id: "ls-nl-36", name: "Tôi mừng vui", tags: ["NL"], season: "ORDINARY", page: "45" },
  { id: "ls-nl-37", name: "Tôi muốn hát bài ca", tags: ["NL"], season: "ORDINARY", page: "48" },
  { id: "ls-nl-38", name: "Trăm triệu lời ca", tags: ["NL"], season: "ORDINARY", page: "49" },
  { id: "ls-nl-39", name: "Trước Nhan Chúa", tags: ["NL"], season: "ORDINARY", page: "50" },
  { id: "ls-nl-40", name: "Vào đền thánh", tags: ["NL"], season: "ORDINARY", page: "52" },
  { id: "ls-nl-41", name: "Vào nhà Chúa", tags: ["NL"], season: "ORDINARY", page: "54" },
  { id: "ls-nl-42", name: "Vào thánh lễ", tags: ["NL"], season: "ORDINARY", page: "53" },
  { id: "ls-nl-43", name: "Về bên Chúa", tags: ["NL"], season: "ORDINARY", page: "56" },
  { id: "ls-nl-44", name: "Về đây hỡi người", tags: ["NL"], season: "ORDINARY", page: "60" },
  { id: "ls-nl-45", name: "Về nhà Chúa 1", tags: ["NL"], season: "ORDINARY", page: "57" },
  { id: "ls-nl-46", name: "Về nhà Chúa 2", tags: ["NL"], season: "ORDINARY", page: "58" },
  { id: "ls-nl-47", name: "Về nơi đây", tags: ["NL"], season: "ORDINARY", page: "61" },
  { id: "ls-nl-48", name: "Xin dẫn con về núi thánh", tags: ["NL"], season: "ORDINARY", page: "62" },
  // --- DÂNG LỄ (71 songs) ---
  { id: "ls-dl-1", name: "Bài ca dâng hiến", tags: ["DL"], season: "ORDINARY", page: "65" },
  { id: "ls-dl-2", name: "Bánh rượu tình thương", tags: ["DL"], season: "ORDINARY", page: "64" },
  { id: "ls-dl-3", name: "Ca dâng lễ", tags: ["DL"], season: "ORDINARY", page: "66" },
  { id: "ls-dl-4", name: "Chúng con Dâng", tags: ["DL"], season: "ORDINARY", page: "67" },
  { id: "ls-dl-5", name: "Có gì để dâng", tags: ["DL"], season: "ORDINARY", page: "68" },
  { id: "ls-dl-6", name: "Con xin dâng", tags: ["DL"], season: "ORDINARY", page: "69" },
  { id: "ls-dl-7", name: "Con xin dâng lên", tags: ["DL"], season: "ORDINARY", page: "81" },
  { id: "ls-dl-8", name: "Con xin tiến dâng", tags: ["DL"], season: "ORDINARY", page: "70" },
  { id: "ls-dl-9", name: "Của lễ con dâng", tags: ["DL"], season: "ORDINARY", page: "71" },
  { id: "ls-dl-10", name: "Của lễ đời con", tags: ["DL"], season: "ORDINARY", page: "74" },
  { id: "ls-dl-11", name: "Của lễ tình yêu", tags: ["DL"], season: "ORDINARY", page: "72" },
  { id: "ls-dl-12", name: "Cùng tấm bánh", tags: ["DL"], season: "ORDINARY", page: "125" },
  { id: "ls-dl-13", name: "Cùng tiến dâng 1", tags: ["DL"], season: "ORDINARY", page: "75" },
  { id: "ls-dl-14", name: "Cùng tiến dâng 2", tags: ["DL"], season: "ORDINARY", page: "76" },
  { id: "ls-dl-15", name: "Dâng 1", tags: ["DL"], season: "ORDINARY", page: "77" },
  { id: "ls-dl-16", name: "Dâng 2", tags: ["DL"], season: "ORDINARY", page: "78" },
  { id: "ls-dl-17", name: "Dâng 3", tags: ["DL"], season: "ORDINARY", page: "79" },
  { id: "ls-dl-18", name: "Dâng 4", tags: ["DL"], season: "ORDINARY", page: "80" },
  { id: "ls-dl-19", name: "Dâng bánh rượu", tags: ["DL"], season: "ORDINARY", page: "82" },
  { id: "ls-dl-20", name: "Dâng Chúa 1", tags: ["DL"], season: "ORDINARY", page: "84" },
  { id: "ls-dl-21", name: "Dâng Chúa 2", tags: ["DL"], season: "ORDINARY", page: "111" },
  { id: "ls-dl-22", name: "Dâng Chúa Trời", tags: ["DL"], season: "ORDINARY", page: "135" },
  { id: "ls-dl-23", name: "Dâng lễ vật", tags: ["DL"], season: "ORDINARY", page: "83" },
  { id: "ls-dl-24", name: "Dâng lên 1", tags: ["DL"], season: "ORDINARY", page: "85" },
  { id: "ls-dl-25", name: "Dâng lên 2", tags: ["DL"], season: "ORDINARY", page: "115" },
  { id: "ls-dl-26", name: "Dâng lên Ba Ngôi", tags: ["DL"], season: "ORDINARY", page: "86" },
  { id: "ls-dl-27", name: "Dâng lên Chúa 1", tags: ["DL"], season: "ORDINARY", page: "87" },
  { id: "ls-dl-28", name: "Dâng lên Chúa 2", tags: ["DL"], season: "ORDINARY", page: "88" },
  { id: "ls-dl-29", name: "Dâng lên Chúa 3", tags: ["DL"], season: "ORDINARY", page: "89" },
  { id: "ls-dl-30", name: "Dâng lên Chúa 4", tags: ["DL"], season: "ORDINARY", page: "90" },
  { id: "ls-dl-31", name: "Dâng lên Chúa bánh thơm", tags: ["DL"], season: "ORDINARY", page: "91" },
  { id: "ls-dl-32", name: "Dâng lên lễ vật", tags: ["DL"], season: "ORDINARY", page: "92" },
  { id: "ls-dl-33", name: "Dâng niềm cảm mến", tags: ["DL"], season: "ORDINARY", page: "93" },
  { id: "ls-dl-34", name: "Dâng trọn cuộc đời", tags: ["DL"], season: "ORDINARY", page: "94" },
  { id: "ls-dl-35", name: "Đây bánh miến", tags: ["DL"], season: "ORDINARY", page: "95" },
  { id: "ls-dl-36", name: "Đây hy lễ", tags: ["DL"], season: "ORDINARY", page: "103" },
  { id: "ls-dl-37", name: "Giờ đây chúng con", tags: ["DL"], season: "ORDINARY", page: "96" },
  { id: "ls-dl-38", name: "Hiến lễ giao hòa", tags: ["DL"], season: "ORDINARY", page: "97" },
  { id: "ls-dl-39", name: "Hiến lễ tình yêu", tags: ["DL"], season: "ORDINARY", page: "98" },
  { id: "ls-dl-40", name: "Hiệp dâng", tags: ["DL"], season: "ORDINARY", page: "100" },
  { id: "ls-dl-41", name: "Khúc tri ân", tags: ["DL"], season: "ORDINARY", page: "102" },
  { id: "ls-dl-42", name: "Kinh dâng", tags: ["DL"], season: "ORDINARY", page: "101" },
  { id: "ls-dl-43", name: "Kính dâng Ngài", tags: ["DL"], season: "ORDINARY", page: "107" },
  { id: "ls-dl-44", name: "Lạy Chúa xin cho lời con", tags: ["DL"], season: "ORDINARY", page: "104" },
  { id: "ls-dl-45", name: "Lấy gì đáp đền", tags: ["DL"], season: "ORDINARY", page: "106" },
  { id: "ls-dl-46", name: "Lễ dâng 1", tags: ["DL"], season: "ORDINARY", page: "108" },
  { id: "ls-dl-47", name: "Lễ dâng 2", tags: ["DL"], season: "ORDINARY", page: "109" },
  { id: "ls-dl-48", name: "Lễ dâng 3", tags: ["DL"], season: "ORDINARY", page: "110" },
  { id: "ls-dl-49", name: "Lễ dâng hiệp nhất", tags: ["DL"], season: "ORDINARY", page: "112" },
  { id: "ls-dl-50", name: "Lễ vật hòa bình", tags: ["DL"], season: "ORDINARY", page: "113" },
  { id: "ls-dl-51", name: "Lễ vật tình yêu", tags: ["DL"], season: "ORDINARY", page: "114" },
  { id: "ls-dl-52", name: "Lời chân thành", tags: ["DL"], season: "ORDINARY", page: "117" },
  { id: "ls-dl-53", name: "Lời dâng", tags: ["DL"], season: "ORDINARY", page: "116" },
  { id: "ls-dl-54", name: "Mỗi lời kinh", tags: ["DL"], season: "ORDINARY", page: "118" },
  { id: "ls-dl-55", name: "Này con xin dâng", tags: ["DL"], season: "ORDINARY", page: "119" },
  { id: "ls-dl-56", name: "Này là", tags: ["DL"], season: "ORDINARY", page: "129" },
  { id: "ls-dl-57", name: "Này từng giọt rượu", tags: ["DL"], season: "ORDINARY", page: "120" },
  { id: "ls-dl-58", name: "Nếu con chợt nhớ", tags: ["DL"], season: "ORDINARY", page: "121" },
  { id: "ls-dl-59", name: "Nguyện dâng lên Chúa 1", tags: ["DL"], season: "ORDINARY", page: "122" },
  { id: "ls-dl-60", name: "Nguyện dâng lên Chúa 2", tags: ["DL"], season: "ORDINARY", page: "124" },
  { id: "ls-dl-61", name: "Tấm bánh ly rượu", tags: ["DL"], season: "ORDINARY", page: "126" },
  { id: "ls-dl-62", name: "Tặng vật dâng Ngài", tags: ["DL"], season: "ORDINARY", page: "128" },
  { id: "ls-dl-63", name: "Thân lúa miến", tags: ["DL"], season: "ORDINARY", page: "127" },
  { id: "ls-dl-64", name: "Tiến dâng", tags: ["DL"], season: "ORDINARY", page: "130" },
  { id: "ls-dl-65", name: "Tiến dâng lên", tags: ["DL"], season: "ORDINARY", page: "131" },
  { id: "ls-dl-66", name: "Trên đĩa thánh", tags: ["DL"], season: "ORDINARY", page: "132" },
  { id: "ls-dl-67", name: "Tựa làn trầm hương", tags: ["DL"], season: "ORDINARY", page: "133" },
  { id: "ls-dl-68", name: "Tựa trầm hương", tags: ["DL"], season: "ORDINARY", page: "134" },
  { id: "ls-dl-69", name: "Xin dâng đời con", tags: ["DL"], season: "ORDINARY", page: "136" },
  { id: "ls-dl-70", name: "Xin dâng lên 1", tags: ["DL"], season: "ORDINARY", page: "137" },
  { id: "ls-dl-71", name: "Xin dâng lên 2", tags: ["DL"], season: "ORDINARY", page: "138" },
  // --- CA NGUYỆN (116 songs) ---
  { id: "ls-cn-1", name: "Bài ca hiệp nhất", tags: ["HL"], season: "ORDINARY", page: "140" },
  { id: "ls-cn-2", name: "Bài ca trên núi", tags: ["HL"], season: "ORDINARY", page: "142" },
  { id: "ls-cn-3", name: "Bàn tay cứu độ", tags: ["HL"], season: "ORDINARY", page: "144" },
  { id: "ls-cn-4", name: "Bao nhiêu hồng ân", tags: ["HL"], season: "ORDINARY", page: "146" },
  { id: "ls-cn-5", name: "Biết Chúa, biết con", tags: ["HL"], season: "ORDINARY", page: "148" },
  { id: "ls-cn-6", name: "Bỏ Ngài con biết theo ai?", tags: ["HL"], season: "ORDINARY", page: "141" },
  { id: "ls-cn-7", name: "Bốn mùa yêu thương", tags: ["HL"], season: "ORDINARY", page: "150" },
  { id: "ls-cn-8", name: "Ca khúc hồng ân", tags: ["HL"], season: "ORDINARY", page: "152" },
  { id: "ls-cn-9", name: "Ca khúc tạ ơn", tags: ["HL"], season: "ORDINARY", page: "154" },
  { id: "ls-cn-10", name: "Ca khúc trầm hương", tags: ["HL"], season: "ORDINARY", page: "156" },
  { id: "ls-cn-11", name: "Ca tình tri ân", tags: ["HL"], season: "ORDINARY", page: "162" },
  { id: "ls-cn-12", name: "Cảm tạ ơn Chúa", tags: ["HL"], season: "ORDINARY", page: "158" },
  { id: "ls-cn-13", name: "Cát biển sao trời", tags: ["HL"], season: "ORDINARY", page: "160" },
  { id: "ls-cn-14", name: "Chính nhờ Ngài", tags: ["HL"], season: "ORDINARY", page: "164" },
  { id: "ls-cn-15", name: "Cho con biết yêu thương", tags: ["HL"], season: "ORDINARY", page: "166" },
  { id: "ls-cn-16", name: "Cho con đến với Ngài", tags: ["HL"], season: "ORDINARY", page: "168" },
  { id: "ls-cn-17", name: "Cho con vững tin", tags: ["HL"], season: "ORDINARY", page: "170" },
  { id: "ls-cn-18", name: "Cho tình tôi nguyên vẹn", tags: ["HL"], season: "ORDINARY", page: "172" },
  { id: "ls-cn-19", name: "Chúa chăn nuôi tôi 1", tags: ["HL"], season: "ORDINARY", page: "174" },
  { id: "ls-cn-20", name: "Chúa chăn nuôi tôi 2", tags: ["HL"], season: "ORDINARY", page: "176" },
  { id: "ls-cn-21", name: "Chúa chiên lành", tags: ["HL"], season: "ORDINARY", page: "163" },
  { id: "ls-cn-22", name: "Chúa đã yêu con", tags: ["HL"], season: "ORDINARY", page: "180" },
  { id: "ls-cn-23", name: "Chúa dẫn con", tags: ["HL"], season: "ORDINARY", page: "178" },
  { id: "ls-cn-24", name: "Chúa khoan nhân", tags: ["HL"], season: "ORDINARY", page: "182" },
  { id: "ls-cn-25", name: "Chúa là con đường", tags: ["HL"], season: "ORDINARY", page: "184" },
  { id: "ls-cn-26", name: "Chúa là gia nghiệp", tags: ["HL"], season: "ORDINARY", page: "186" },
  { id: "ls-cn-27", name: "Chúa là tất cả đời con", tags: ["HL"], season: "ORDINARY", page: "188" },
  { id: "ls-cn-28", name: "Chúa là tình yêu", tags: ["HL"], season: "ORDINARY", page: "179" },
  { id: "ls-cn-29", name: "Chúa luôn còn mãi", tags: ["HL"], season: "ORDINARY", page: "190" },
  { id: "ls-cn-30", name: "Chúa nâng con lên", tags: ["HL"], season: "ORDINARY", page: "192" },
  { id: "ls-cn-31", name: "Chúa ngự trong con", tags: ["HL"], season: "ORDINARY", page: "193" },
  { id: "ls-cn-32", name: "Chúa ở bên con", tags: ["HL"], season: "ORDINARY", page: "194" },
  { id: "ls-cn-33", name: "Chúa sống trong tôi", tags: ["HL"], season: "ORDINARY", page: "196" },
  { id: "ls-cn-34", name: "Chúa yêu con", tags: ["HL"], season: "ORDINARY", page: "198" },
  { id: "ls-cn-35", name: "Chúng con cần đến Chúa", tags: ["HL"], season: "ORDINARY", page: "200" },
  { id: "ls-cn-36", name: "Chứng nhân tình yêu", tags: ["HL"], season: "ORDINARY", page: "202" },
  { id: "ls-cn-37", name: "Có bao giờ", tags: ["HL"], season: "ORDINARY", page: "204" },
  { id: "ls-cn-38", name: "Có Chúa trong đời", tags: ["HL"], season: "ORDINARY", page: "197" },
  { id: "ls-cn-39", name: "Con chỉ là tạo vật", tags: ["HL"], season: "ORDINARY", page: "208" },
  { id: "ls-cn-40", name: "Con đây vẫn tin", tags: ["HL"], season: "ORDINARY", page: "210" },
  { id: "ls-cn-41", name: "Con đường bé nhỏ", tags: ["HL"], season: "ORDINARY", page: "206" },
  { id: "ls-cn-42", name: "Con gặp Chúa", tags: ["HL"], season: "ORDINARY", page: "212" },
  { id: "ls-cn-43", name: "Còn gì dâng Ngài", tags: ["HL"], season: "ORDINARY", page: "207" },
  { id: "ls-cn-44", name: "Con không xin", tags: ["HL"], season: "ORDINARY", page: "216" },
  { id: "ls-cn-45", name: "Con tin Chúa ơi", tags: ["HL"], season: "ORDINARY", page: "218" },
  { id: "ls-cn-46", name: "Con trông cậy Chúa", tags: ["HL"], season: "ORDINARY", page: "220" },
  { id: "ls-cn-47", name: "Con xin đức ái", tags: ["HL"], season: "ORDINARY", page: "222" },
  { id: "ls-cn-48", name: "Dẫn con từng bước 1", tags: ["HL"], season: "ORDINARY", page: "224" },
  { id: "ls-cn-49", name: "Dẫn con từng bước 2", tags: ["HL"], season: "ORDINARY", page: "226" },
  { id: "ls-cn-50", name: "Dâng lời ngợi ca", tags: ["HL"], season: "ORDINARY", page: "228" },
  { id: "ls-cn-51", name: "Đến dự tiệc thánh", tags: ["HL"], season: "ORDINARY", page: "230" },
  { id: "ls-cn-52", name: "Đẹp thay những bước chân", tags: ["HL"], season: "ORDINARY", page: "232" },
  { id: "ls-cn-53", name: "Đồng cỏ tươi", tags: ["HL"], season: "ORDINARY", page: "234" },
  { id: "ls-cn-54", name: "Đồng xanh thơ", tags: ["HL"], season: "ORDINARY", page: "236" },
  { id: "ls-cn-55", name: "Dù con chưa thấy Ngài", tags: ["HL"], season: "ORDINARY", page: "238" },
  { id: "ls-cn-56", name: "Đường con đi", tags: ["HL"], season: "ORDINARY", page: "240" },
  { id: "ls-cn-57", name: "Gia nghiệp đời con", tags: ["HL"], season: "ORDINARY", page: "242" },
  { id: "ls-cn-58", name: "Giêsu ánh sáng", tags: ["HL"], season: "ORDINARY", page: "199" },
  { id: "ls-cn-59", name: "Giữ gìn con", tags: ["HL"], season: "ORDINARY", page: "214" },
  { id: "ls-cn-60", name: "Giữa cảnh đời", tags: ["HL"], season: "ORDINARY", page: "215" },
  { id: "ls-cn-61", name: "Gọi lời yêu thương", tags: ["HL"], season: "ORDINARY", page: "244" },
  { id: "ls-cn-62", name: "Hạnh phúc thay", tags: ["HL"], season: "ORDINARY", page: "246" },
  { id: "ls-cn-63", name: "Hát về tình yêu Chúa", tags: ["HL"], season: "ORDINARY", page: "248" },
  { id: "ls-cn-64", name: "Hoan ca tạ ơn", tags: ["HL"], season: "ORDINARY", page: "247" },
  { id: "ls-cn-65", name: "Hỡi Người tôi yêu dấu", tags: ["HL"], season: "ORDINARY", page: "250" },
  { id: "ls-cn-66", name: "Hồng ân Thiên Chúa", tags: ["HL"], season: "ORDINARY", page: "252" },
  { id: "ls-cn-67", name: "Hy vọng vào Ngài", tags: ["HL"], season: "ORDINARY", page: "254" },
  { id: "ls-cn-68", name: "Kinh hòa bình", tags: ["HL"], season: "ORDINARY", page: "256" },
  { id: "ls-cn-69", name: "Kinh nguyện con dâng", tags: ["HL"], season: "ORDINARY", page: "258" },
  { id: "ls-cn-70", name: "Lắng nghe Lời Chúa", tags: ["HL"], season: "ORDINARY", page: "260" },
  { id: "ls-cn-71", name: "Lạy Chúa bao ngày tháng", tags: ["HL"], season: "ORDINARY", page: "201" },
  { id: "ls-cn-72", name: "Lời hằng sống", tags: ["HL"], season: "ORDINARY", page: "262" },
  { id: "ls-cn-73", name: "Lời kinh cho một ngày", tags: ["HL"], season: "ORDINARY", page: "264" },
  { id: "ls-cn-74", name: "Lời kinh cuộc đời", tags: ["HL"], season: "ORDINARY", page: "266" },
  { id: "ls-cn-75", name: "Lối Ngài bước đi", tags: ["HL"], season: "ORDINARY", page: "235" },
  { id: "ls-cn-76", name: "Lời thiêng 1", tags: ["HL"], season: "ORDINARY", page: "268" },
  { id: "ls-cn-77", name: "Lời thiêng 2", tags: ["HL"], season: "ORDINARY", page: "270" },
  { id: "ls-cn-78", name: "Lửa hồng ngàn đời", tags: ["HL"], season: "ORDINARY", page: "263" },
  { id: "ls-cn-79", name: "Mở lòng", tags: ["HL"], season: "ORDINARY", page: "272" },
  { id: "ls-cn-80", name: "Mơ về bên Chúa", tags: ["HL"], season: "ORDINARY", page: "274" },
  { id: "ls-cn-81", name: "Muôn tạo vật ơi", tags: ["HL"], season: "ORDINARY", page: "276" },
  { id: "ls-cn-82", name: "Này Ngài đã đến", tags: ["HL"], season: "ORDINARY", page: "278" },
  { id: "ls-cn-83", name: "Nếu Chúa là", tags: ["HL"], season: "ORDINARY", page: "275" },
  { id: "ls-cn-84", name: "Nguồn ánh sáng", tags: ["HL"], season: "ORDINARY", page: "280" },
  { id: "ls-cn-85", name: "Nguồn sống yêu thương", tags: ["HL"], season: "ORDINARY", page: "282" },
  { id: "ls-cn-86", name: "Nguồn suối an bình", tags: ["HL"], season: "ORDINARY", page: "284" },
  { id: "ls-cn-87", name: "Nguồn trợ lực đời tôi", tags: ["HL"], season: "ORDINARY", page: "286" },
  { id: "ls-cn-88", name: "Nhạc khúc yêu thương", tags: ["HL"], season: "ORDINARY", page: "288" },
  { id: "ls-cn-89", name: "Nhìn lên nhan Chúa", tags: ["HL"], season: "ORDINARY", page: "289" },
  { id: "ls-cn-90", name: "Như con thơ", tags: ["HL"], season: "ORDINARY", page: "290" },
  { id: "ls-cn-91", name: "Như Thầy yêu thương", tags: ["HL"], season: "ORDINARY", page: "292" },
  { id: "ls-cn-92", name: "Niềm vui trong Chúa", tags: ["HL"], season: "ORDINARY", page: "294" },
  { id: "ls-cn-93", name: "Nơi con nương ẩn", tags: ["HL"], season: "ORDINARY", page: "296" },
  { id: "ls-cn-94", name: "Ở đâu có bác ái", tags: ["HL"], season: "ORDINARY", page: "295" },
  { id: "ls-cn-95", name: "Ôi nhiệm mầu", tags: ["HL"], season: "ORDINARY", page: "298" },
  { id: "ls-cn-96", name: "Sống trong niềm vui", tags: ["HL"], season: "ORDINARY", page: "302" },
  { id: "ls-cn-97", name: "Sống trong tình Chúa", tags: ["HL"], season: "ORDINARY", page: "304" },
  { id: "ls-cn-98", name: "Sống với Chúa 1", tags: ["HL"], season: "ORDINARY", page: "299" },
  { id: "ls-cn-99", name: "Sống với Chúa 2", tags: ["HL"], season: "ORDINARY", page: "300" },
  { id: "ls-cn-306", name: "101 Thắp sáng lên", tags: ["HL"], season: "ORDINARY", page: "307" },
  { id: "ls-cn-308", name: "103 Tìm về chân thiện mỹ", tags: ["HL"], season: "ORDINARY", page: "310" },
  { id: "ls-cn-312", name: "105 Tình ca tri ân", tags: ["HL"], season: "ORDINARY", page: "314" },
  { id: "ls-cn-316", name: "107 Tình Cha", tags: ["HL"], season: "ORDINARY", page: "311" },
  { id: "ls-cn-317", name: "109 Tình Chúa tình con", tags: ["HL"], season: "ORDINARY", page: "318" },
  { id: "ls-cn-319", name: "111 Tình Ngài sưởi ấm lòng con", tags: ["HL"], season: "ORDINARY", page: "320" },
  { id: "ls-cn-324", name: "114 Tình yêu của Chúa", tags: ["HL"], season: "ORDINARY", page: "326" },
  { id: "ls-cn-328", name: "116 Tình yêu thương vời vợi", tags: ["HL"], season: "ORDINARY", page: "330" },
  { id: "ls-cn-287", name: "118 Tôi tin Chúa thương tôi", tags: ["HL"], season: "ORDINARY", page: "332" },
  { id: "ls-cn-334", name: "120 Trời bể bao la", tags: ["HL"], season: "ORDINARY", page: "336" },
  { id: "ls-cn-338", name: "122 Từ bây giờ", tags: ["HL"], season: "ORDINARY", page: "331" },
  { id: "ls-cn-340", name: "124 Ước mơ trong con", tags: ["HL"], season: "ORDINARY", page: "342" },
  { id: "ls-cn-344", name: "126 Về bên Chúa", tags: ["HL"], season: "ORDINARY", page: "346" },
  { id: "ls-cn-348", name: "128 Xin chỉ cho con", tags: ["HL"], season: "ORDINARY", page: "350" },
  { id: "ls-cn-352", name: "130 Xin giữ con", tags: ["HL"], season: "ORDINARY", page: "354" },
  { id: "ls-cn-355", name: "132 Xin tri ân 1", tags: ["HL"], season: "ORDINARY", page: "356" },
  { id: "ls-cn-357", name: "134 Xin trở nên thạch động", tags: ["HL"], season: "ORDINARY", page: "358" },
  // --- THÁNH THỂ (34 songs) ---
  { id: "ls-tt-1", name: "Ân tình Chúa", tags: ["HL"], season: "ORDINARY", page: "694" },
  { id: "ls-tt-2", name: "Bằng tất cả tình yêu", tags: ["HL"], season: "ORDINARY", page: "695" },
  { id: "ls-tt-3", name: "Bánh Thiêng", tags: ["HL"], season: "ORDINARY", page: "700" },
  { id: "ls-tt-4", name: "Bí tích tình yêu", tags: ["HL"], season: "ORDINARY", page: "696" },
  { id: "ls-tt-5", name: "Cầu cho Đức Giáo Hoàng", tags: ["HL"], season: "ORDINARY", page: "725" },
  { id: "ls-tt-6", name: "Chính Mình Máu Chúa", tags: ["HL"], season: "ORDINARY", page: "698" },
  { id: "ls-tt-7", name: "Chúa đã yêu con", tags: ["HL"], season: "ORDINARY", page: "701" },
  { id: "ls-tt-8", name: "Con muốn chúc mừng", tags: ["HL"], season: "ORDINARY", page: "704" },
  { id: "ls-tt-9", name: "Con quỳ gối", tags: ["HL"], season: "ORDINARY", page: "702" },
  { id: "ls-tt-10", name: "Con thờ lạy", tags: ["HL"], season: "ORDINARY", page: "705" },
  { id: "ls-tt-11", name: "Đây nhiệm tích 1", tags: ["HL"], season: "ORDINARY", page: "703" },
  { id: "ls-tt-12", name: "Đây nhiệm tích 2", tags: ["HL"], season: "ORDINARY", page: "706" },
  { id: "ls-tt-13", name: "Đây phép nhiệm mầu", tags: ["HL"], season: "ORDINARY", page: "707" },
  { id: "ls-tt-14", name: "Giêsu tình yêu", tags: ["HL"], season: "ORDINARY", page: "708" },
  { id: "ls-tt-15", name: "Hãy đến với Ta", tags: ["HL"], season: "ORDINARY", page: "709" },
  { id: "ls-tt-16", name: "Lòng Chúa ái tuất", tags: ["HL"], season: "ORDINARY", page: "710" },
  { id: "ls-tt-17", name: "Lương thực của con", tags: ["HL"], season: "ORDINARY", page: "711" },
  { id: "ls-tt-18", name: "Mầu nhiệm yêu thương", tags: ["HL"], season: "ORDINARY", page: "712" },
  { id: "ls-tt-19", name: "Ngắm Mình Thánh Chúa", tags: ["HL"], season: "ORDINARY", page: "714" },
  { id: "ls-tt-20", name: "Người ơi hãy đến", tags: ["HL"], season: "ORDINARY", page: "716" },
  { id: "ls-tt-21", name: "Nguyện yêu Chúa", tags: ["HL"], season: "ORDINARY", page: "715" },
  { id: "ls-tt-22", name: "Ôi Thần Linh Chúa", tags: ["HL"], season: "ORDINARY", page: "718" },
  { id: "ls-tt-23", name: "Phút linh thiêng", tags: ["HL"], season: "ORDINARY", page: "719" },
  { id: "ls-tt-24", name: "Phút than thở", tags: ["HL"], season: "ORDINARY", page: "720" },
  { id: "ls-tt-25", name: "Quỳ trước nhan Ngài", tags: ["HL"], season: "ORDINARY", page: "721" },
  { id: "ls-tt-26", name: "Ta là Bánh Hằng Sống", tags: ["HL"], season: "ORDINARY", page: "722" },
  { id: "ls-tt-27", name: "Tantum Ergo 1", tags: ["HL"], season: "ORDINARY", page: "717" },
  { id: "ls-tt-28", name: "Tantum Ergo 2", tags: ["HL"], season: "ORDINARY", page: "727" },
  { id: "ls-tt-29", name: "Thành tâm thờ kính", tags: ["HL"], season: "ORDINARY", page: "723" },
  { id: "ls-tt-30", name: "Thờ lạy Chúa", tags: ["HL"], season: "ORDINARY", page: "724" },
  { id: "ls-tt-31", name: "Thờ lạy tin yêu", tags: ["HL"], season: "ORDINARY", page: "726" },
  { id: "ls-tt-32", name: "Tình yêu Chúa", tags: ["HL"], season: "ORDINARY", page: "728" },
  { id: "ls-tt-33", name: "Tôn thờ Tình Yêu Chúa", tags: ["HL"], season: "ORDINARY", page: "729" },
  { id: "ls-tt-34", name: "Trước Thánh Thể", tags: ["HL"], season: "ORDINARY", page: "730" },
  // --- KẾT LỄ (40 songs) ---
  { id: "ls-kl-1", name: "Cảm tạ hồng ân", tags: ["KL"], season: "ORDINARY", page: "360" },
  { id: "ls-kl-2", name: "Cho mọi người hiệp nhất", tags: ["KL"], season: "ORDINARY", page: "363" },
  { id: "ls-kl-3", name: "Cho một tình yêu", tags: ["KL"], season: "ORDINARY", page: "362" },
  { id: "ls-kl-4", name: "Chúa sai con đi", tags: ["KL"], season: "ORDINARY", page: "364" },
  { id: "ls-kl-5", name: "Chứng nhân Tin Mừng", tags: ["KL"], season: "ORDINARY", page: "366" },
  { id: "ls-kl-6", name: "Con xin làm chứng tá", tags: ["KL"], season: "ORDINARY", page: "368" },
  { id: "ls-kl-7", name: "Cùng Mẹ tạ lễ", tags: ["KL"], season: "ORDINARY", page: "361" },
  { id: "ls-kl-8", name: "Cùng vui bước", tags: ["KL"], season: "ORDINARY", page: "367" },
  { id: "ls-kl-9", name: "Đâu có tình yêu thương", tags: ["KL"], season: "ORDINARY", page: "370" },
  { id: "ls-kl-10", name: "Đem Tin Mừng", tags: ["KL"], season: "ORDINARY", page: "365" },
  { id: "ls-kl-11", name: "Đi gieo Tin Mừng", tags: ["KL"], season: "ORDINARY", page: "371" },
  { id: "ls-kl-12", name: "Đường đi có Chúa", tags: ["KL"], season: "ORDINARY", page: "372" },
  { id: "ls-kl-13", name: "Giờ đây Chúa sai tôi", tags: ["KL"], season: "ORDINARY", page: "373" },
  { id: "ls-kl-14", name: "Hồng ân Thiên Chúa", tags: ["KL"], season: "ORDINARY", page: "374" },
  { id: "ls-kl-15", name: "Khúc hát tạ ơn", tags: ["KL"], season: "ORDINARY", page: "375" },
  { id: "ls-kl-16", name: "Kinh tạ lễ", tags: ["KL"], season: "ORDINARY", page: "369" },
  { id: "ls-kl-17", name: "Lạy Chúa xin hãy sai", tags: ["KL"], season: "ORDINARY", page: "376" },
  { id: "ls-kl-18", name: "Lễ hết", tags: ["KL"], season: "ORDINARY", page: "377" },
  { id: "ls-kl-19", name: "Lễ xong rồi", tags: ["KL"], season: "ORDINARY", page: "379" },
  { id: "ls-kl-20", name: "Lên đường", tags: ["KL"], season: "ORDINARY", page: "378" },
  { id: "ls-kl-21", name: "Lời nguyện truyền giáo", tags: ["KL"], season: "ORDINARY", page: "383" },
  { id: "ls-kl-22", name: "Này chính Chúa", tags: ["KL"], season: "ORDINARY", page: "380" },
  { id: "ls-kl-23", name: "Nhân chứng phúc âm", tags: ["KL"], season: "ORDINARY", page: "381" },
  { id: "ls-kl-24", name: "Như Giêsu", tags: ["KL"], season: "ORDINARY", page: "362" },
  { id: "ls-kl-25", name: "Ra về", tags: ["KL"], season: "ORDINARY", page: "384" },
  { id: "ls-kl-26", name: "Ra về an bình", tags: ["KL"], season: "ORDINARY", page: "382" },
  { id: "ls-kl-27", name: "Sống cho Tin Mừng", tags: ["KL"], season: "ORDINARY", page: "385" },
  { id: "ls-kl-28", name: "Sống chứng nhân", tags: ["KL"], season: "ORDINARY", page: "386" },
  { id: "ls-kl-29", name: "Tạ ơn", tags: ["KL"], season: "ORDINARY", page: "382" },
  { id: "ls-kl-30", name: "Tạ ơn Chúa với Mẹ", tags: ["KL"], season: "ORDINARY", page: "387" },
  { id: "ls-kl-31", name: "Ta ra về", tags: ["KL"], season: "ORDINARY", page: "388" },
  { id: "ls-kl-32", name: "Tán tụng hồng ân", tags: ["KL"], season: "ORDINARY", page: "390" },
  { id: "ls-kl-33", name: "Thánh lễ đã hết", tags: ["KL"], season: "ORDINARY", page: "389" },
  { id: "ls-kl-34", name: "Thánh lễ trong cuộc đời", tags: ["KL"], season: "ORDINARY", page: "388" },
  { id: "ls-kl-35", name: "Thắp sáng trong con", tags: ["KL"], season: "ORDINARY", page: "392" },
  { id: "ls-kl-36", name: "Theo bước Người", tags: ["KL"], season: "ORDINARY", page: "393" },
  { id: "ls-kl-38", name: "Trong an bình", tags: ["KL"], season: "ORDINARY", page: "395" },
  { id: "ls-kl-39", name: "Vì Chúa là Tình Yêu", tags: ["KL"], season: "ORDINARY", page: "396" },
  { id: "ls-kl-40", name: "Xin cho con", tags: ["KL"], season: "ORDINARY", page: "397" },
  { id: "ls-kl-41", name: "Xin ngợi khen Cha", tags: ["KL"], season: "ORDINARY", page: "398" },
  // --- MÙA VỌNG (35 songs) ---
  { id: "ls-mv-1", name: "Ca nhập lễ", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "400" },
  { id: "ls-mv-2", name: "Hãy sẵn sàng", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "401" },
  { id: "ls-mv-3", name: "Chúa sẽ đến", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "402" },
  { id: "ls-mv-4", name: "Để Chúa đến", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "404" },
  { id: "ls-mv-5", name: "Đợi trông", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "406" },
  { id: "ls-mv-6", name: "Hãy dọn đường", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "405" },
  { id: "ls-mv-7", name: "Hãy tỉnh thức", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "408" },
  { id: "ls-mv-8", name: "Hãy vùng đứng", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "410" },
  { id: "ls-mv-9", name: "Hướng tâm hồn lên", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "412" },
  { id: "ls-mv-10", name: "Lễ dâng trông đợi", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "414" },
  { id: "ls-mv-11", name: "Lời vọng", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "407" },
  { id: "ls-mv-12", name: "Maranatha xin Ngài hãy đến", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "416" },
  { id: "ls-mv-13", name: "Mau dọn đường Chúa", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "419" },
  { id: "ls-mv-14", name: "Mau mau dọn đường", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "417" },
  { id: "ls-mv-15", name: "Mây ơi mưa xuống", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "418" },
  { id: "ls-mv-16", name: "Mưa ơi", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "415" },
  { id: "ls-mv-17", name: "Nguyện Mùa Vọng", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "420" },
  { id: "ls-mv-18", name: "Nguyện trời cao", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "421" },
  { id: "ls-mv-19", name: "Nước Trời đã gần", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "422" },
  { id: "ls-mv-20", name: "Tiếng gọi trong sa mạc", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "424" },
  { id: "ls-mv-21", name: "Trời cao", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "437" },
  { id: "ls-mv-22", name: "Trời cao hỡi 1", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "429" },
  { id: "ls-mv-23", name: "Trời cao hỡi 2", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "430" },
  { id: "ls-mv-24", name: "Trông chờ Chúa đến", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "428" },
  { id: "ls-mv-25", name: "Trông đợi", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "427" },
  { id: "ls-mv-26", name: "Trong rừng sâu", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "426" },
  { id: "ls-mv-27", name: "Trung tín đợi chờ", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "432" },
  { id: "ls-mv-28", name: "Vì Chúa sẽ đến", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "434" },
  { id: "ls-mv-29", name: "Vui lên", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "436" },
  { id: "ls-mv-30", name: "Vui lên anh em", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "438" },
  { id: "ls-mv-31", name: "Vui lên Chúa sắp đến rồi", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "442" },
  { id: "ls-mv-32", name: "Vui lên Sion", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "435" },
  { id: "ls-mv-33", name: "Xin Chúa đến 1", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "423" },
  { id: "ls-mv-34", name: "Xin Chúa đến 2", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "440" },
  { id: "ls-mv-35", name: "Xin gieo sương", tags: ["NL", "DL", "HL", "KL"], season: "ADVENT", page: "441" },
  // --- MÙA GIÁNG SINH (34 songs) ---
  { id: "ls-gs-2", name: "Adeste Fideles", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "446" },
  { id: "ls-gs-3", name: "Ba vua đăng trình", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "444" },
  { id: "ls-gs-4", name: "Chúa đã sinh ra", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "447" },
  { id: "ls-gs-5", name: "Chúa thương loài người", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "450" },
  { id: "ls-gs-6", name: "Chúng ta lên đường", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "479" },
  { id: "ls-gs-7", name: "Dâng Chúa đêm nay", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "454" },
  { id: "ls-gs-8", name: "Dâng Hài Nhi", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "452" },
  { id: "ls-gs-9", name: "Đêm nay bừng sáng", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "453" },
  { id: "ls-gs-10", name: "Đêm Noel", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "458" },
  { id: "ls-gs-11", name: "Đêm thánh vô cùng", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "456" },
  { id: "ls-gs-12", name: "Hang Belem", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "460" },
  { id: "ls-gs-13", name: "Hội nhạc thiên quốc", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "462" },
  { id: "ls-gs-14", name: "Lễ Hiển Linh", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "457" },
  { id: "ls-gs-15", name: "Lễ vật giáng sinh", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "464" },
  { id: "ls-gs-16", name: "Loài người ơi", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "465" },
  { id: "ls-gs-17", name: "Lời cầu nửa đêm", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "466" },
  { id: "ls-gs-18", name: "Lời ru thánh", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "459" },
  { id: "ls-gs-19", name: "Màn đêm lung linh", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "468" },
  { id: "ls-gs-20", name: "Một hài nhi 1", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "469" },
  { id: "ls-gs-21", name: "Một hài nhi 2", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "483" },
  { id: "ls-gs-22", name: "Mùa đông năm ấy", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "470" },
  { id: "ls-gs-23", name: "Nhịp đàn đêm giáng sinh", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "472" },
  { id: "ls-gs-24", name: "Niềm vui Giáng Sinh", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "474" },
  { id: "ls-gs-25", name: "Noel về", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "478" },
  { id: "ls-gs-26", name: "Noel! Noel!", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "476" },
  { id: "ls-gs-27", name: "Nơi Bê-lem", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "473" },
  { id: "ls-gs-28", name: "Tâm tình hòa bình", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "477" },
  { id: "ls-gs-29", name: "Tiếng hát thiên thần", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "480" },
  { id: "ls-gs-30", name: "Tiếng muôn thiên thần", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "482" },
  { id: "ls-gs-31", name: "Tình Trời vinh sáng", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "484" },
  { id: "ls-gs-32", name: "Trời hân hoan", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "485" },
  { id: "ls-gs-33", name: "Trong hang đá nhỏ 1", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "486" },
  { id: "ls-gs-34", name: "Trong hang đá nhỏ 2", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "488" },
  { id: "ls-gs-35", name: "Xin Ngài ở giữa chúng con", tags: ["NL", "DL", "HL", "KL"], season: "CHRISTMAS", page: "490" },
  // --- MÙA CHAY (63 songs) ---
  { id: "ls-mc-1", name: "Bài ca thống hối", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "492" },
  { id: "ls-mc-2", name: "Bài ca thương khó", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "494" },
  { id: "ls-mc-3", name: "Bao giờ", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "496" },
  { id: "ls-mc-4", name: "Chờ mong", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "498" },
  { id: "ls-mc-5", name: "Chúa không lầm", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "499" },
  { id: "ls-mc-6", name: "Chúa thương cứu độ", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "500" },
  { id: "ls-mc-7", name: "Chúa vào thành", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "502" },
  { id: "ls-mc-8", name: "Chút lòng son", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "504" },
  { id: "ls-mc-9", name: "Con đường Chúa đã đi qua", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "506" },
  { id: "ls-mc-10", name: "Con nâng hồn lên", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "508" },
  { id: "ls-mc-11", name: "Con nay trở về", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "510" },
  { id: "ls-mc-12", name: "Còn tình yêu nào", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "505" },
  { id: "ls-mc-13", name: "Con vươn hồn lên", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "512" },
  { id: "ls-mc-14", name: "Cứ dấu này", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "503" },
  { id: "ls-mc-15", name: "Của lễ nhân sinh", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "514" },
  { id: "ls-mc-16", name: "Cuộc đời là bể dâu", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "516" },
  { id: "ls-mc-17", name: "Dân ta ơi", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "518" },
  { id: "ls-mc-18", name: "Đừng bỏ con Chúa ơi", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "520" },
  { id: "ls-mc-19", name: "Đường thập tự", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "522" },
  { id: "ls-mc-20", name: "Giêsu Giêsu", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "524" },
  { id: "ls-mc-21", name: "Giờ tử nạn", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "523" },
  { id: "ls-mc-22", name: "Giọt lệ sầu", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "515" },
  { id: "ls-mc-23", name: "Giọt lệ thống hối", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "526" },
  { id: "ls-mc-24", name: "Hạt giống tình yêu", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "528" },
  { id: "ls-mc-25", name: "Hãy quay về", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "497" },
  { id: "ls-mc-26", name: "Hãy trở về", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "530" },
  { id: "ls-mc-27", name: "Hãy trỗi dậy", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "527" },
  { id: "ls-mc-28", name: "Kinh Chay", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "531" },
  { id: "ls-mc-29", name: "Lễ tế đầu mùa", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "529" },
  { id: "ls-mc-30", name: "Luật yêu thương", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "532" },
  { id: "ls-mc-31", name: "Máu chiên bò", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "519" },
  { id: "ls-mc-32", name: "Một thoáng mây bay", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "536" },
  { id: "ls-mc-33", name: "Mùa hồng ân", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "534" },
  { id: "ls-mc-34", name: "Nếu hạt lúa", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "538" },
  { id: "ls-mc-35", name: "Ngươi là bụi tro", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "537" },
  { id: "ls-mc-36", name: "Nguyện Chúa chí ái", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "517" },
  { id: "ls-mc-37", name: "Những chiếc mạng nhện", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "540" },
  { id: "ls-mc-38", name: "Niềm tâm sự", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "542" },
  { id: "ls-mc-39", name: "Phó thác", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "544" },
  { id: "ls-mc-40", name: "Phù hoa nối tiếp phù hoa", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "545" },
  { id: "ls-mc-41", name: "Quỳ bên cung thánh", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "546" },
  { id: "ls-mc-42", name: "Quyết trở về với Cha", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "547" },
  { id: "ls-mc-43", name: "Tâm tình sám hối", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "548" },
  { id: "ls-mc-44", name: "Thân bụi tro", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "554" },
  { id: "ls-mc-45", name: "Thân phận lưu đày", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "552" },
  { id: "ls-mc-46", name: "Thánh giá hiên ngang", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "550" },
  { id: "ls-mc-47", name: "Thập giá Đức Kitô", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "553" },
  { id: "ls-mc-48", name: "Thập giá minh chứng tình yêu", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "555" },
  { id: "ls-mc-49", name: "Thập Giá ngất cao", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "556" },
  { id: "ls-mc-50", name: "Thập Giá tình yêu và hy vọng", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "558" },
  { id: "ls-mc-51", name: "Tình phụ tử", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "560" },
  { id: "ls-mc-52", name: "Tình yêu Chúa vút cao", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "562" },
  { id: "ls-mc-53", name: "Tình yêu Thánh Giá", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "564" },
  { id: "ls-mc-54", name: "Tình yêu Thập Giá", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "566" },
  { id: "ls-mc-55", name: "Trái tim tinh tuyền", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "568" },
  { id: "ls-mc-56", name: "Vang lời tụng ca", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "557" },
  { id: "ls-mc-57", name: "Vinh dự của chúng ta", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "521" },
  { id: "ls-mc-58", name: "Vinh quang của ta", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "575" },
  { id: "ls-mc-59", name: "Vươn cao linh hồn", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "570" },
  { id: "ls-mc-60", name: "Xin cho đời tôi", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "572" },
  { id: "ls-mc-61", name: "Xin dâng", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "578" },
  { id: "ls-mc-62", name: "Xin dắt đưa con về", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "574" },
  { id: "ls-mc-63", name: "Xin thương con", tags: ["NL", "DL", "HL", "KL"], season: "LENT", page: "576" },
  // --- MÙA PHỤC SINH (87 songs) ---
  { id: "ls-ps-1", name: "Alleluia", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "581" },
  { id: "ls-ps-2", name: "Alleluia Chúa sống lại", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "583" },
  { id: "ls-ps-3", name: "Ánh sáng Chúa Kitô", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "580" },
  { id: "ls-ps-4", name: "Ánh sáng vinh quang", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "627" },
  { id: "ls-ps-5", name: "Bài ca cho người chiến thắng", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "584" },
  { id: "ls-ps-6", name: "Bài ca đức tin", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "586" },
  { id: "ls-ps-7", name: "Chúa chiến thắng khải hoàn", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "588" },
  { id: "ls-ps-8", name: "Chúa đã lên trời", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "590" },
  { id: "ls-ps-9", name: "Chúa đã sống lại", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "589" },
  { id: "ls-ps-10", name: "Chúa hiển trị", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "592" },
  { id: "ls-ps-11", name: "Chúa lên trời 1", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "594" },
  { id: "ls-ps-12", name: "Chúa lên trời 2", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "595" },
  { id: "ls-ps-13", name: "Chúa nay đã Phục Sinh", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "601" },
  { id: "ls-ps-14", name: "Chúa sống lại rồi", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "596" },
  { id: "ls-ps-15", name: "Chúa về trời, con ra đi", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "598" },
  { id: "ls-ps-16", name: "Con hãy nhớ", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "599" },
  { id: "ls-ps-17", name: "Con hãy nhớ rằng", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "600" },
  { id: "ls-ps-18", name: "Dâng lời cảm mến", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "602" },
  { id: "ls-ps-19", name: "Được sai đi", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "604" },
  { id: "ls-ps-20", name: "Giờ Chúa Phục Sinh", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "603" },
  { id: "ls-ps-21", name: "Hát mừng chiến thắng", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "606" },
  { id: "ls-ps-22", name: "Hát mừng Chúa", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "608" },
  { id: "ls-ps-23", name: "Hoan ca Phục Sinh 1", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "610" },
  { id: "ls-ps-24", name: "Hoan ca Phục Sinh 2", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "614" },
  { id: "ls-ps-25", name: "Hôm nay mừng Chúa lên trời", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "607" },
  { id: "ls-ps-26", name: "Hy tế tuyệt vời", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "613" },
  { id: "ls-ps-27", name: "Khải hoàn ca", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "616" },
  { id: "ls-ps-28", name: "Khúc hát vượt qua", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "618" },
  { id: "ls-ps-29", name: "Lễ Phục Sinh và Thăng Thiên", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "617" },
  { id: "ls-ps-30", name: "Lễ tế", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "620" },
  { id: "ls-ps-31", name: "Mạch suối cứu độ", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "622" },
  { id: "ls-ps-32", name: "Mừng Chúa Phục Sinh", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "624" },
  { id: "ls-ps-33", name: "Mừng Chúa sống lại", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "626" },
  { id: "ls-ps-34", name: "Mừng vui lên (Regina Caeli)", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "581" },
  { id: "ls-ps-35", name: "Nào hãy mừng vui", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "625" },
  { id: "ls-ps-36", name: "Này chị Maria Mađalêna", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "628" },
  { id: "ls-ps-37", name: "Này người ngủ mê", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "630" },
  { id: "ls-ps-38", name: "Ngày Chúa khải hoàn", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "631" },
  { id: "ls-ps-39", name: "Ngày Thiên Chúa tạo thành", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "632" },
  { id: "ls-ps-40", name: "Nhân trần vui lên", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "634" },
  { id: "ls-ps-41", name: "Niềm vui chiến thắng", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "636" },
  { id: "ls-ps-42", name: "Thánh ca Phục Sinh", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "633" },
  { id: "ls-ps-43", name: "Tiến ca phục sinh", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "638" },
  { id: "ls-ps-44", name: "Tin sống lại", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "639" },
  { id: "ls-ps-45", name: "Tình Chúa xót thương", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "640" },
  { id: "ls-ps-46", name: "Tôi đã thấy nước", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "582" },
  { id: "ls-ps-47", name: "Tôma, hãy tin", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "641" },
  { id: "ls-ps-48", name: "Trên bàn thờ trần thế", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "643" },
  { id: "ls-ps-49", name: "Trên đường Emmau", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "642" },
  { id: "ls-ps-50", name: "Trong ánh lửa Phục Sinh", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "644" },
  { id: "ls-ps-51", name: "Vang lên", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "646" },
  { id: "ls-ps-1", name: "Cầu xin Chúa Thánh Thần", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "648" },
  { id: "ls-ps-2", name: "Hãy chiếu soi", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "649" },
  { id: "ls-ps-3", name: "Lạy Chúa Thánh Thần 1", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "650" },
  { id: "ls-ps-4", name: "Lạy Chúa Thánh Thần 2", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "651" },
  { id: "ls-ps-5", name: "Lạy Chúa Thánh Thần 3", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "661" },
  { id: "ls-ps-6", name: "Nguyện Chúa Thánh Thần", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "652" },
  { id: "ls-ps-7", name: "Thần linh Chúa", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "658" },
  { id: "ls-ps-8", name: "Thánh Thần hãy đến", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "654" },
  { id: "ls-ps-9", name: "Thánh Thần Tình Yêu", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "653" },
  { id: "ls-ps-10", name: "Thánh Thần xin hãy đến", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "656" },
  { id: "ls-ps-11", name: "Trong ơn Chúa Thánh Thần", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "662" },
  { id: "ls-ps-12", name: "Xin ban Thần Trí", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "655" },
  { id: "ls-ps-13", name: "Xin Chúa Ngôi Ba", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "657" },
  { id: "ls-ps-14", name: "Xin Ngôi Ba", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "660" },
  { id: "ls-ps-1", name: "Giêsu vua muôn vua", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "664" },
  { id: "ls-ps-2", name: "Giêsu vua tình yêu 1", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "666" },
  { id: "ls-ps-3", name: "Giêsu vua tình yêu 2", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "668" },
  { id: "ls-ps-4", name: "Hát lên bài ca mới", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "670" },
  { id: "ls-ps-5", name: "Hoan hô vua Giêsu 1", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "667" },
  { id: "ls-ps-6", name: "Hoan hô vua Giêsu 2", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "672" },
  { id: "ls-ps-7", name: "Lạy Chúa là Vua", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "674" },
  { id: "ls-ps-8", name: "Lòng thương xót Chúa", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "676" },
  { id: "ls-ps-9", name: "Một giọt sương", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "678" },
  { id: "ls-ps-10", name: "Nguyện Thánh Tâm", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "680" },
  { id: "ls-ps-11", name: "Thánh Tâm Chúa Giêsu", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "687" },
  { id: "ls-ps-12", name: "Thánh Tâm Giêsu Vua", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "673" },
  { id: "ls-ps-13", name: "Thương xót như Chúa Cha", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "682" },
  { id: "ls-ps-14", name: "Tình Chúa yêu con", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "684" },
  { id: "ls-ps-15", name: "Tôn vinh lòng thương xót Chúa", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "686" },
  { id: "ls-ps-16", name: "Tôn vương Thánh Tâm", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "669" },
  { id: "ls-ps-17", name: "Trái tim Người", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "681" },
  { id: "ls-ps-18", name: "Trong trái tim Chúa yêu", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "688" },
  { id: "ls-ps-19", name: "Từ trái tim", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "690" },
  { id: "ls-ps-20", name: "Về nơi đây", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "691" },
  { id: "ls-ps-21", name: "Vinh danh Ba Ngôi 1", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "683" },
  { id: "ls-ps-22", name: "Vinh danh Ba Ngôi 2", tags: ["NL", "DL", "HL", "KL"], season: "EASTER", page: "692" },
  // --- ĐỨC MẸ (71 songs) ---
  { id: "ls-dm-1", name: "Ave Maria", tags: ["KL"], season: "ORDINARY", page: "761" },
  { id: "ls-dm-2", name: "Ave Maria 1", tags: ["KL"], season: "ORDINARY", page: "732" },
  { id: "ls-dm-3", name: "Ave Maria 2", tags: ["KL"], season: "ORDINARY", page: "734" },
  { id: "ls-dm-4", name: "Ave Maria, con dâng lời", tags: ["KL"], season: "ORDINARY", page: "736" },
  { id: "ls-dm-5", name: "Bài ca dâng Mẹ", tags: ["KL"], season: "ORDINARY", page: "745" },
  { id: "ls-dm-6", name: "Bài ca không quên", tags: ["KL"], season: "ORDINARY", page: "795" },
  { id: "ls-dm-7", name: "Cành hoa dâng Mẹ", tags: ["KL"], season: "ORDINARY", page: "735" },
  { id: "ls-dm-8", name: "Chút tình con thơ", tags: ["KL"], season: "ORDINARY", page: "738" },
  { id: "ls-dm-9", name: "Con xin dâng Mẹ", tags: ["KL"], season: "ORDINARY", page: "740" },
  { id: "ls-dm-10", name: "Cung chúc Trinh Vương", tags: ["KL"], season: "ORDINARY", page: "742" },
  { id: "ls-dm-11", name: "Dâng lễ với Mẹ", tags: ["KL"], season: "ORDINARY", page: "739" },
  { id: "ls-dm-12", name: "Dâng Mẹ", tags: ["KL"], season: "ORDINARY", page: "744" },
  { id: "ls-dm-13", name: "Dâng Mẹ đời con", tags: ["KL"], season: "ORDINARY", page: "746" },
  { id: "ls-dm-14", name: "Dâng mình cho Đức Mẹ", tags: ["KL"], season: "ORDINARY", page: "747" },
  { id: "ls-dm-15", name: "Dâng về Mẹ", tags: ["KL"], season: "ORDINARY", page: "805" },
  { id: "ls-dm-16", name: "Dao ca Mẹ dịu hiền", tags: ["KL"], season: "ORDINARY", page: "748" },
  { id: "ls-dm-17", name: "Đền tạ trái tim Mẹ", tags: ["KL"], season: "ORDINARY", page: "750" },
  { id: "ls-dm-18", name: "Dưới áo mẹ từ bi", tags: ["KL"], season: "ORDINARY", page: "752" },
  { id: "ls-dm-19", name: "Hoa Mân Côi", tags: ["KL"], season: "ORDINARY", page: "753" },
  { id: "ls-dm-20", name: "Hoa Mân Côi kính Mẹ", tags: ["KL"], season: "ORDINARY", page: "754" },
  { id: "ls-dm-21", name: "Hoan ca Maria", tags: ["KL"], season: "ORDINARY", page: "741" },
  { id: "ls-dm-22", name: "Kìa ai", tags: ["KL"], season: "ORDINARY", page: "757" },
  { id: "ls-dm-23", name: "Kính chào Nữ Vương", tags: ["KL"], season: "ORDINARY", page: "756" },
  { id: "ls-dm-24", name: "Kinh đầu lễ", tags: ["KL"], season: "ORDINARY", page: "758" },
  { id: "ls-dm-25", name: "Lặng ngắm Mẹ", tags: ["KL"], season: "ORDINARY", page: "760" },
  { id: "ls-dm-26", name: "Lạy Đức Mẹ Chúa Trời", tags: ["KL"], season: "ORDINARY", page: "749" },
  { id: "ls-dm-27", name: "Lạy Mẹ mến yêu", tags: ["KL"], season: "ORDINARY", page: "762" },
  { id: "ls-dm-28", name: "Lạy Mẹ xin yên ủi", tags: ["KL"], season: "ORDINARY", page: "759" },
  { id: "ls-dm-29", name: "Linh hồn tôi 1", tags: ["KL"], season: "ORDINARY", page: "764" },
  { id: "ls-dm-30", name: "Linh hồn tôi 2", tags: ["KL"], season: "ORDINARY", page: "766" },
  { id: "ls-dm-31", name: "Linh hồn tôi ca lên", tags: ["KL"], season: "ORDINARY", page: "768" },
  { id: "ls-dm-32", name: "Lời cầu cho xứ đạo", tags: ["KL"], season: "ORDINARY", page: "770" },
  { id: "ls-dm-33", name: "Lời Mẹ nhắn nhủ", tags: ["KL"], season: "ORDINARY", page: "771" },
  { id: "ls-dm-34", name: "Lòng Mẹ từ nhân", tags: ["KL"], season: "ORDINARY", page: "807" },
  { id: "ls-dm-35", name: "Maria diễm lệ", tags: ["KL"], season: "ORDINARY", page: "775" },
  { id: "ls-dm-36", name: "Maria Mẹ hằng cứu giúp", tags: ["KL"], season: "ORDINARY", page: "772" },
  { id: "ls-dm-37", name: "Mẹ Chúa vinh quang", tags: ["KL"], season: "ORDINARY", page: "773" },
  { id: "ls-dm-38", name: "Mẹ đầy ơn phúc", tags: ["KL"], season: "ORDINARY", page: "774" },
  { id: "ls-dm-39", name: "Mẹ đẹp tươi 1", tags: ["KL"], season: "ORDINARY", page: "776" },
  { id: "ls-dm-40", name: "Mẹ đẹp tươi 2", tags: ["KL"], season: "ORDINARY", page: "777" },
  { id: "ls-dm-41", name: "Mẹ đứng đó", tags: ["KL"], season: "ORDINARY", page: "778" },
  { id: "ls-dm-42", name: "Mẹ hiệp công", tags: ["KL"], season: "ORDINARY", page: "780" },
  { id: "ls-dm-43", name: "Mẹ là", tags: ["KL"], season: "ORDINARY", page: "781" },
  { id: "ls-dm-44", name: "Mẹ là bóng mát", tags: ["KL"], season: "ORDINARY", page: "782" },
  { id: "ls-dm-45", name: "Mẹ là mùa xuân", tags: ["KL"], season: "ORDINARY", page: "784" },
  { id: "ls-dm-46", name: "Mẹ Maria", tags: ["KL"], season: "ORDINARY", page: "783" },
  { id: "ls-dm-47", name: "Mẹ nhân loại", tags: ["KL"], season: "ORDINARY", page: "786" },
  { id: "ls-dm-48", name: "Mẹ ơi!", tags: ["KL"], season: "ORDINARY", page: "787" },
  { id: "ls-dm-49", name: "Mẹ tuyệt mỹ", tags: ["KL"], season: "ORDINARY", page: "785" },
  { id: "ls-dm-50", name: "Ngàn hoa đẹp tươi", tags: ["KL"], season: "ORDINARY", page: "788" },
  { id: "ls-dm-51", name: "Những cánh hoa dâng Mẹ", tags: ["KL"], season: "ORDINARY", page: "789" },
  { id: "ls-dm-52", name: "Niềm cậy trông", tags: ["KL"], season: "ORDINARY", page: "793" },
  { id: "ls-dm-53", name: "Nữ Vương hòa bình", tags: ["KL"], season: "ORDINARY", page: "790" },
  { id: "ls-dm-54", name: "Nữ Vương Mân Côi", tags: ["KL"], season: "ORDINARY", page: "794" },
  { id: "ls-dm-55", name: "Nữ Vương Thiên Đàng", tags: ["KL"], season: "ORDINARY", page: "796" },
  { id: "ls-dm-56", name: "Sao mai đưa lối", tags: ["KL"], season: "ORDINARY", page: "798" },
  { id: "ls-dm-58", name: "Tâm ca đồng hành", tags: ["KL"], season: "ORDINARY", page: "800" },
  { id: "ls-dm-59", name: "Tận hiến cho Đức Mẹ", tags: ["KL"], season: "ORDINARY", page: "801" },
  { id: "ls-dm-60", name: "Tấu lạy Bà", tags: ["KL"], season: "ORDINARY", page: "802" },
  { id: "ls-dm-61", name: "Tiếng gọi Fatima", tags: ["KL"], season: "ORDINARY", page: "803" },
  { id: "ls-dm-62", name: "Tiếng hát thiên thu", tags: ["KL"], season: "ORDINARY", page: "804" },
  { id: "ls-dm-63", name: "Tiếng lòng cảm mến", tags: ["KL"], season: "ORDINARY", page: "806" },
  { id: "ls-dm-64", name: "Tràng hoa Mân Côi 1", tags: ["KL"], season: "ORDINARY", page: "808" },
  { id: "ls-dm-65", name: "Tràng hoa Mân Côi 2", tags: ["KL"], season: "ORDINARY", page: "810" },
  { id: "ls-dm-66", name: "Trinh vương Maria", tags: ["KL"], season: "ORDINARY", page: "809" },
  { id: "ls-dm-67", name: "Trước nhan Mẹ", tags: ["KL"], season: "ORDINARY", page: "812" },
  { id: "ls-dm-68", name: "Từ lúc Mẹ nói lời xin vâng", tags: ["KL"], season: "ORDINARY", page: "813" },
  { id: "ls-dm-69", name: "Tung hô Nữ Vương", tags: ["KL"], season: "ORDINARY", page: "814" },
  { id: "ls-dm-70", name: "Vòng hoa dâng Mẹ", tags: ["KL"], season: "ORDINARY", page: "816" },
  { id: "ls-dm-71", name: "Xin vâng 1", tags: ["KL"], season: "ORDINARY", page: "815" },
  { id: "ls-dm-72", name: "Xin vâng 2", tags: ["KL"], season: "ORDINARY", page: "818" },
];

export const SEASONS = {
  ADVENT: "ADVENT",
  CHRISTMAS: "CHRISTMAS",
  LENT: "LENT",
  EASTER: "EASTER",
  ORDINARY: "ORDINARY",
};
